<?xml version="1.0" encoding="utf-8"?><Database Name="1gb_x_odessa" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ms-sql-6.in-solve.ru;Initial Catalog=1gb_x_odessa;Persist Security Info=True;User ID=1gb_odessa-gb" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[__MigrationHistory]" Member="__MigrationHistory">
    <Type Name="__MigrationHistory">
      <Column Name="MigrationId" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ContextKey" Type="System.String" DbType="NVarChar(300) NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ProductVersion" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Settings" Member="Settings">
    <Type Name="Settings">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="setting_key" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="setting_value" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetRoles" Member="AspNetRoles">
    <Type Name="AspNetRoles">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserClaims" Member="AspNetUserClaims">
    <Type Name="AspNetUserClaims">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ClaimType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClaimValue" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserLogins" Member="AspNetUserLogins">
    <Type Name="AspNetUserLogins">
      <Column Name="LoginProvider" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ProviderKey" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserRoles" Member="AspNetUserRoles">
    <Type Name="AspNetUserRoles">
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUsers" Member="AspNetUsers">
    <Type Name="AspNetUsers">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.languages" Member="languages">
    <Type Name="languages">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="language" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LiveConditions" Member="LiveConditions">
    <Type Name="LiveConditions">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lc_key" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lc_value" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Objects_Attributes" Member="Objects_Attributes">
    <Type Name="Objects_Attributes">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="attribute_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Attributes_Objects_Attributes" Member="Attributes" ThisKey="attribute_id" OtherKey="id" Type="Attributes" IsForeignKey="true" />
      <Association Name="Objects_Objects_Attributes" Member="Objects" ThisKey="object_id" OtherKey="ID" Type="Objects" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pages" Member="Pages">
    <Type Name="Pages">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Naim" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Alias" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phrase" Member="Phrase">
    <Type Name="Phrase">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="phrase_key" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phrases_languages" Member="Phrases_languages">
    <Type Name="Phrases_languages">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="lang_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="phrase_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.reviews" Member="reviews">
    <Type Name="reviews">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cleaness" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="services" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comfort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="region" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="object_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="header" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="body" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Attributes" Member="Attributes">
    <Type Name="Attributes">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="attr_key" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="picture" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Attributes_Objects_Attributes" Member="Objects_Attributes" ThisKey="id" OtherKey="attribute_id" Type="Objects_Attributes" />
    </Type>
  </Table>
  <Table Name="dbo.Region" Member="Region">
    <Type Name="Region">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Naim" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="Region_Objects" Member="Objects" ThisKey="ID" OtherKey="region_id" Type="Objects" />
    </Type>
  </Table>
  <Table Name="dbo.Objects" Member="Objects">
    <Type Name="Objects">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="region_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="header" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="rooms_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="guests_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="price1" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="price2" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="price5" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="price14" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="rate" Type="System.Decimal" DbType="Decimal(18,1)" CanBeNull="true" />
      <Column Name="desc_body" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="pic1large" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="pic2large" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="pic1" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="pic2" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="pic3" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="pic4" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Objects_Objects_Attributes" Member="Objects_Attributes" ThisKey="ID" OtherKey="object_id" Type="Objects_Attributes" />
      <Association Name="Region_Objects" Member="Region" ThisKey="region_id" OtherKey="ID" Type="Region" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Objects_LiveConditions" Member="Objects_LiveConditions">
    <Type Name="Objects_LiveConditions">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="object_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="lc_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[_value]" Member="_value" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
</Database>